name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "stable"
          - "1.23"
          - "1.22"
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
          - "1.17"
          - "1.16"
          - "1.15"
          - "1.14"
          - "1.13"
          - "1.12"
          - "1.11"
          - "1.10"
          - "1.9"
          - "1.8"
          - "1.7"
          - "1.6"
          - "1.5"
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: "on"
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v5
        with:
          path: src/github.com/${{ github.repository }}

      - name: Test
        run: |
          go test -v -coverprofile=profile.cov ./...
        working-directory: src/github.com/${{ github.repository }}

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          parallel: true
          working-directory: src/github.com/${{ github.repository }}
          flag-name: ${{ matrix.go }}

  # notifies that all test jobs are finished.
  finish:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
