name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.17.x"
          - "1.16.x"
          - "1.15.x"
          - "1.14.x"
          - "1.13.x"
          - "1.12.x"
          - "1.11.x"
          - "1.10.x"
          - "1.9.x"
          - "1.8.x"
          - "1.7.x"
          - "1.6.x"
          - "1.5.x"
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: "on"
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v2
        with:
          path: src/github.com/${{ github.repository }}

      - name: Test
        run: |
          go test -v -coverprofile=profile.cov ./...
        working-directory: src/github.com/${{ github.repository }}

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          parallel: true
          working-directory: src/github.com/${{ github.repository }}
          flag-name: ${{ matrix.go }}

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
